version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - RedisConnectionString=redis:6379
    env_file:
      - "Environments/.env.${env}"
    depends_on:
      - redis

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes


