version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - REDIS_CONNECTION_STRING=redis:6379,password=8Cz^!Kbs9m05
    env_file:
      - "Environments/.env.${env}"
    depends_on:
      - redis

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379
    environment:
      - REDIS_PASSWORD=8Cz^!Kbs9m05
    volumes:
      - data:/data

volumes:
  data:
  

