apiVersion: v1
kind: Secret
metadata:
  name: viennarocks
type: Opaque
data:
  TicketMasterApiKey: QW9MZ0JhbXlEVUsydVAxV0dtSXdEUGhwSXY1cFlSMDQ=
  REDIS_PASSWORD: NnNRVENAQF52VDEz
  REDIS_CONNECTION_STRING: cmVkaXM6NjM3OSxwYXNzd29yZD02c1FUQ0BAXnZUMTM=

