apiVersion: apps/v1
kind: Deployment
metadata:
  name: viennarocks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: viennarocks
  template:
    metadata:
      labels:
        app: viennarocks
    spec:
      containers:
      - name: api
        image: se22m001/viennarocks:latest
        env:
          - name: TicketMasterApiKey
            valueFrom:
              secretKeyRef:
                name: viennarocks
                key: TicketMasterApiKey
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: viennarocks
                key: ASPNETCORE_ENVIRONMENT
          - name: REDIS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: viennarocks
                key: REDIS_CONNECTION_STRING
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 443
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: viennarocks
spec:
  type: LoadBalancer
  selector:
    app: viennarocks
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: http
    port: 80
    targetPort: 80


