apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: api
          image: se22m001/viennarocks:latest
          env:
            - name: TicketMasterApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: TicketMasterApiKey
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ if .Values.isDevelopment }}DEVELOPMENT{{ else }}Production{{ end }}
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: REDIS_CONNECTION_STRING
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 443
            - containerPort: 80
