apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-redis
    spec:
      containers:
      - name: redis
        env:
          {{- include "secret" (dict "name" .Release.Name "key" "REDIS_PASSWORD") | indent 12  }}
        image: bitnami/redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 6379

