apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-redis
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}-redis
  ports:
  - port: 6379
    targetPort: 6379