apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  TicketMasterApiKey: {{ .Values.secrets.TicketMasterApiKey | b64enc }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | b64enc }}
  REDIS_CONNECTION_STRING: {{ .Values.secrets.REDIS_CONNECTION_STRING | b64enc }}

